language: java
script: 
- mvn package -Popenshift
- rvm install ruby-1.8.7-p374
- rvm use 1.8.7
- gem install rhc
- rhc apps --token bc282a3d95b04784e1d20994499862a14bc35875dbfcbbf1544e8c10bb25d1c3

deploy:
  provider: openshift
  user: hivanamaced@gmail.com
  password: passwordgcm
  app: calculadora
  domain: hivanah
  on:
    repo: hivanamcd/calculadora


