language: java
script: 
- mvn package -Popenshift
- git checkout 539342274382ecce120002dd@calculadora-hivanah.rhcloud.com/~/git/calculadora.git
- git add . 
- git config --global user.email "hivanapd@gmail.com"
- git config --global user.name "hivanamcd"
- git config --global user.name "hivana1"
- git commit -a -m "commit"
- git push origin master



